name: Bug Report
description: Report a bug with the game
title: "[BUG] - Describe bug briefly"
labels: [bug, triage]

body:
- type: markdown
  attributes:
    value: |
      - Write a descriptive issue title above.
      - Search [open](https://github.com/comfyjase/godot-cpp-template/issues) and [closed](https://github.com/comfyjase/godot-cpp-template/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.

- type: input
  attributes:
    label: System Information
    description: |
      - Specify the platform you saw this bug on.
    placeholder: Windows 10
  validations:
    required: true
    
- type: input
  attributes:
    label: Build Information
    description: |
      - Specify the build you played (the name of the artifact you downloaded from Github Actions).
    placeholder: game_linux_template_debug_x86_64_single_05262025_224744_main_7ac79ff
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe the Bug
    description: |
      - List of clear steps to reproduce the bug.
      - What is the expected result?
      - What is the actual result?
      - Please include any videos/screenshots (max 10MB) below. **NOTE: Do not select another field until your files are finished uploading.**
    placeholder: |
      Example:
        Reproduction steps:
            1. Start the game.
            2. Play through naturally or use debug commands to start level 2.
            3. Wait for cutscene to finish.
            4. Observe the player character is invisible.
        
        Expected result:
        Player character should be visible after the cutscene has finished.
        
        Actual result:
        Player character remains invisible.
  validations:
    required: true