name: 🤖 Android
on:
  workflow_call:

env:
  ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
  ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

jobs:
  build-and-export:
    #timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            #{ platform: android, arch: arm32, os: ubuntu-22.04 },
            { platform: android, arch: arm64, os: ubuntu-22.04 },
            #{ platform: android, arch: x86_32, os: ubuntu-22.04 },
            #{ platform: android, arch: x86_64, os: ubuntu-22.04 },
          ]
        # Leaving here for future reference if you need to make more flavours of builds you can specify these here.
        #target-type: [template_debug, template_release, profile, production]
        #float-precision: [single, double]
        target-type: [production]
        float-precision: [single]
    
    runs-on: ${{ matrix.target.os }}
    steps:
      # Clone this repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Setup dependencies
      - name: Setup godot-cpp
        uses: ./godot-cpp/.github/actions/setup-godot-cpp
        with:
          platform: ${{ matrix.target.platform }}

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
  
      - name: Download pre-built Android Swappy Frame Pacing Library
        uses: dsaltares/fetch-gh-release-asset@1.1.2
        with:
          repo: godotengine/godot-swappy
          version: tags/from-source-2025-01-31
          file: godot-swappy.7z
          target: swappy/godot-swappy.7z

      - name: Extract pre-built Android Swappy Frame Pacing Library
        run: 7za x -y swappy/godot-swappy.7z -o${{github.workspace}}/godot/thirdparty/swappy-frame-pacing
  
      - name: Setup Workflow Variables
        run: |
          python tools/scripts/write_to_github_actions_environment.py
    
      # Restore .scons_cache
      - name: Restore .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-restore
        with:
          scons-cache: ${{ github.workspace }}/.scons_cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}
      
      # Build Engine + GDExtension (with caches)
      - name: Build Project
        shell: sh
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons_cache/
        run: |
          python tools/scripts/build.py ${{ matrix.target.platform }} ${{ matrix.target-type }} ${{ matrix.target.arch }} ${{ matrix.float-precision }} True
      
      - name: Create Custom Export Template
        shell: sh
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons_cache/
        run: |
          python tools/scripts/create_custom_export_template.py ${{ matrix.target.platform }} ${{ matrix.target-type }} ${{ matrix.target.arch }} ${{ matrix.float-precision }} True
      
      # Save scons cache
      - name: Save .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-save
        with:
          scons-cache: ${{ github.workspace }}/.scons_cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}
        continue-on-error: true
        
      - name: Generate Release Keystore
        if: ${{ matrix.target-type != 'template_debug' && env.ANDROID_KEYSTORE_ALIAS != null && env.ANDROID_KEYSTORE_PASSWORD != null }}
        run: |
          keytool -genkey -keyalg rsa -alias $ANDROID_KEYSTORE_ALIAS -keypass $ANDROID_KEYSTORE_PASSWORD -keystore release.keystore -storepass $ANDROID_KEYSTORE_PASSWORD -dname "cn=android, o=android, c=uk" -validity 9999

      - name: Export Project
        if: ${{ matrix.target-type == 'template_debug' || ( matrix.target-type != 'template_debug' && env.ANDROID_KEYSTORE_ALIAS != null && env.ANDROID_KEYSTORE_PASSWORD != null) }}
        shell: sh
        run: |
          python tools/scripts/export.py ${{ matrix.target.platform }} ${{ matrix.target-type }} ${{ matrix.target.arch }} ${{ matrix.float-precision }} True

      - name: Unit Tests
        if: ${{ matrix.target-type == 'template_debug' }}
        run: |
          python tools/scripts/run_unit_tests.py ${{ matrix.target.platform }} ${{ matrix.target-type }} ${{ matrix.target.arch }} ${{ matrix.float-precision }} True

      # Upload the build
      - name: Upload Artifact
        if: ${{ matrix.target-type == 'template_debug' || ( matrix.target-type != 'template_debug' && env.ANDROID_KEYSTORE_ALIAS != null && env.ANDROID_KEYSTORE_PASSWORD != null) }}
        uses: actions/upload-artifact@v4
        with:
          name: game_${{ matrix.target.platform }}_${{ matrix.target-type }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ env.BUILD_TIME }}_${{ github.ref_name }}_${{ env.SHA_SHORT }}
          path: |
            ${{ github.workspace }}/bin/${{ matrix.target.platform }}/**
